name: AWS - Terraform Create

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: aws

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./aws
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v6

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      # Configure AWS Credentials for AWS CLI and other AWS SDKs and tools
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      # S3 bucket for Terraform state files if it doesn't exist
      - name: Create Bucket tfstate
        run: |
          if aws s3api head-bucket --bucket mechermes-tf-state-aws 2>/dev/null; then
            echo "Bucket already exists"
          else
            aws s3api create-bucket --bucket mechermes-tf-state-aws --region ${{ vars.AWS_DEFAULT_REGION }}
            echo "Bucket created, waiting 60 seconds before continuing..."
            sleep 60
          fi

      # Create DynamoDB table for Terraform state locking if it doesn't exist
      - name: Create DynamoDB Table for tf-locks
        run: |
          if aws dynamodb describe-table --table-name arn:aws:dynamodb:us-east-1:920117427782:table/mechermes-tf-locks 2>/dev/null; then
            echo "DynamoDB table already exists"
          else
            aws dynamodb create-table --table-name arn:aws:dynamodb:us-east-1:920117427782:table/mechermes-tf-locks --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --region ${{ vars.AWS_DEFAULT_REGION }}
            echo "DynamoDB table created, waiting 20 seconds before continuing..."
            sleep 20
          fi

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

      # Build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
